version: '3.8'

services:

  bot:
    image: ats-bot
    env_file:
      - .env
    volumes:
      - ./db/:/app/db
    command: /bin/sh -c "python main.py"

  scheduler:
    network_mode: host
    image: ats-bot
    env_file:
      - .env
    volumes:
      - ./db/:/app/db
    command: /bin/sh -c "python scheduler.py"
